In [1]:
!pip install numpy
!pip install pandas
!pip install pathlib

Requirement already satisfied: numpy in c:\users\adity\appdata\local\programs\python\python313\lib\site-packages (2.3.1)

[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\adity\appdata\local\programs\python\python313\lib\site-packages (2.3.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\adity\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\adity\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\adity\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\adity\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\adity\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting pathlib
  Downloading pathlib-1.0.1-py3-none-any.whl.metadata (5.1 kB)
Downloading pathlib-1.0.1-py3-none-any.whl (14 kB)
Installing collected packages: pathlib
Successfully installed pathlib-1.0.1

[notice] A new release of pip is available: 25.1.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

In [4]:
#common_path = 'C:/Users/adity/Desktop/LRZ Projec
common_path = Path.cwd().parent

#### Instagram Data

In [5]:
insta_data = pd.read_excel(common_path / 'Data' / 'raw' / 'dataset_instagram-scraper_2026-05-13_14-35-13-924.xlsx')

In [6]:
insta_data.describe()

,alt,childPosts/0/alt,childPosts/0/caption,childPosts/0/commentsCount,childPosts/0/dimensionsHeight,childPosts/0/dimensionsWidth,childPosts/0/firstComment,childPosts/0/id,childPosts/0/likesCount,childPosts/0/ownerId,...,musicInfo/should_mute_audio_reason,ownerId,taggedUsers/0/id,taggedUsers/1/id,taggedUsers/2/id,taggedUsers/3/id,taggedUsers/4/id,videoDuration,videoPlayCount,videoViewCount
count,0.0,0.0,0.0,112.0,112.000000,112.000000,0.0,1.120000e+02,0.0,0.0,...,0.0,1.350000e+02,7.700000e+01,2.300000e+01,5.000000e+00,2.000000e+00,1.000000e+00,2.000000,1.0,2.000000
mean,NaN,NaN,NaN,0.0,1063.544643,1067.767857,NaN,3.444301e+18,NaN,NaN,...,NaN,8.608381e+09,1.138268e+10,3.413051e+10,6.380179e+09,4.280019e+09,7.110194e+09,30.866000,3508.0,1250.000000
std,NaN,NaN,NaN,0.0,87.811314,76.272506,NaN,3.324296e+17,NaN,NaN,...,NaN,0.000000e+00,1.819115e+10,2.199269e+10,8.538730e+09,3.825798e+09,NaN,38.466609,NaN,294.156421
min,NaN,NaN,NaN,0.0,480.000000,480.000000,NaN,2.269509e+18,NaN,NaN,...,NaN,8.608381e+09,2.992427e+08,2.992427e+08,7.765857e+08,1.574771e+09,7.110194e+09,3.666000,3508.0,1042.000000
25%,NaN,NaN,NaN,0.0,1080.000000,1080.000000,NaN,3.263851e+18,NaN,NaN,...,NaN,8.608381e+09,1.012347e+09,5.371910e+09,1.794252e+09,2.927395e+09,7.110194e+09,17.266000,3508.0,1146.000000
50%,NaN,NaN,NaN,0.0,1080.000000,1080.000000,NaN,3.587309e+18,NaN,NaN,...,NaN,8.608381e+09,2.504501e+09,4.851918e+10,2.124018e+09,4.280019e+09,7.110194e+09,30.866000,3508.0,1250.000000
75%,NaN,NaN,NaN,0.0,1080.000000,1080.000000,NaN,3.611710e+18,NaN,NaN,...,NaN,8.608381e+09,7.754559e+09,4.910170e+10,5.962504e+09,5.632643e+09,7.110194e+09,44.466000,3508.0,1354.000000
max,NaN,NaN,NaN,0.0,1080.000000,1080.000000,NaN,3.865783e+18,NaN,NaN,...,NaN,8.608381e+09,5.794921e+10,6.219794e+10,2.124353e+10,6.985266e+09,7.110194e+09,58.066000,3508.0,1458.000000

In [7]:
insta_data.shape

(135, 693)

In [8]:
list(insta_data.columns)

['alt',
 'audioUrl',
 'caption',
 'childPosts/0/alt',
 'childPosts/0/caption',
 'childPosts/0/commentsCount',
 'childPosts/0/dimensionsHeight',
 'childPosts/0/dimensionsWidth',
 'childPosts/0/displayUrl',
 'childPosts/0/firstComment',
 'childPosts/0/id',
 'childPosts/0/likesCount',
 'childPosts/0/ownerId',
 'childPosts/0/shortCode',
 'childPosts/0/taggedUsers/0/full_name',
 'childPosts/0/taggedUsers/0/id',
 'childPosts/0/taggedUsers/0/is_verified',
 'childPosts/0/taggedUsers/0/profile_pic_url',
 'childPosts/0/taggedUsers/0/username',
 'childPosts/0/taggedUsers/1/full_name',
 'childPosts/0/taggedUsers/1/id',
 'childPosts/0/taggedUsers/1/is_verified',
 'childPosts/0/taggedUsers/1/profile_pic_url',
 'childPosts/0/taggedUsers/1/username',
 'childPosts/0/taggedUsers/2/full_name',
 'childPosts/0/taggedUsers/2/id',
 'childPosts/0/taggedUsers/2/is_verified',
 'childPosts/0/taggedUsers/2/profile_pic_url',
 'childPosts/0/taggedUsers/2/username',
 'childPosts/0/taggedUsers/3/full_name',
 'childPosts/0/taggedUsers/3/id',
 'childPosts/0/taggedUsers/3/is_verified',
 'childPosts/0/taggedUsers/3/profile_pic_url',
 'childPosts/0/taggedUsers/3/username',
 'childPosts/0/timestamp',
 'childPosts/0/type',
 'childPosts/0/url',
 'childPosts/1/alt',
 'childPosts/1/caption',
 'childPosts/1/commentsCount',
 'childPosts/1/dimensionsHeight',
 'childPosts/1/dimensionsWidth',
 'childPosts/1/displayUrl',
 'childPosts/1/firstComment',
 'childPosts/1/id',
 'childPosts/1/likesCount',
 'childPosts/1/ownerId',
 'childPosts/1/shortCode',
 'childPosts/1/taggedUsers/0/full_name',
 'childPosts/1/taggedUsers/0/id',
 'childPosts/1/taggedUsers/0/is_verified',
 'childPosts/1/taggedUsers/0/profile_pic_url',
 'childPosts/1/taggedUsers/0/username',
 'childPosts/1/taggedUsers/1/full_name',
 'childPosts/1/taggedUsers/1/id',
 'childPosts/1/taggedUsers/1/is_verified',
 'childPosts/1/taggedUsers/1/profile_pic_url',
 'childPosts/1/taggedUsers/1/username',
 'childPosts/1/taggedUsers/2/full_name',
 'childPosts/1/taggedUsers/2/id',
 'childPosts/1/taggedUsers/2/is_verified',
 'childPosts/1/taggedUsers/2/profile_pic_url',
 'childPosts/1/taggedUsers/2/username',
 'childPosts/1/taggedUsers/3/full_name',
 'childPosts/1/taggedUsers/3/id',
 'childPosts/1/taggedUsers/3/is_verified',
 'childPosts/1/taggedUsers/3/profile_pic_url',
 'childPosts/1/taggedUsers/3/username',
 'childPosts/1/timestamp',
 'childPosts/1/type',
 'childPosts/1/url',
 'childPosts/2/alt',
 'childPosts/2/caption',
 'childPosts/2/commentsCount',
 'childPosts/2/dimensionsHeight',
 'childPosts/2/dimensionsWidth',
 'childPosts/2/displayUrl',
 'childPosts/2/firstComment',
 'childPosts/2/id',
 'childPosts/2/likesCount',
 'childPosts/2/ownerId',
 'childPosts/2/shortCode',
 'childPosts/2/taggedUsers/0/full_name',
 'childPosts/2/taggedUsers/0/id',
 'childPosts/2/taggedUsers/0/is_verified',
 'childPosts/2/taggedUsers/0/profile_pic_url',
 'childPosts/2/taggedUsers/0/username',
 'childPosts/2/taggedUsers/1/full_name',
 'childPosts/2/taggedUsers/1/id',
 'childPosts/2/taggedUsers/1/is_verified',
 'childPosts/2/taggedUsers/1/profile_pic_url',
 'childPosts/2/taggedUsers/1/username',
 'childPosts/2/taggedUsers/2/full_name',
 'childPosts/2/taggedUsers/2/id',
 'childPosts/2/taggedUsers/2/is_verified',
 'childPosts/2/taggedUsers/2/profile_pic_url',
 'childPosts/2/taggedUsers/2/username',
 'childPosts/2/taggedUsers/3/full_name',
 'childPosts/2/taggedUsers/3/id',
 'childPosts/2/taggedUsers/3/is_verified',
 'childPosts/2/taggedUsers/3/profile_pic_url',
 'childPosts/2/taggedUsers/3/username',
 'childPosts/2/timestamp',
 'childPosts/2/type',
 'childPosts/2/url',
 'childPosts/3/alt',
 'childPosts/3/caption',
 'childPosts/3/commentsCount',
 'childPosts/3/dimensionsHeight',
 'childPosts/3/dimensionsWidth',
 'childPosts/3/displayUrl',
 'childPosts/3/firstComment',
 'childPosts/3/id',
 'childPosts/3/likesCount',
 'childPosts/3/ownerId',
 'childPosts/3/shortCode',
 'childPosts/3/taggedUsers/0/full_name',
 'childPosts/3/taggedUsers/0/id',
 'childPosts/3/taggedUsers/0/is_verified',
 'childPosts/3/taggedUsers/0/profile_pic_url',
 'childPosts/3/taggedUsers/0/username',
 'childPosts/3/taggedUsers/1/full_name',
 'childPosts/3/taggedUsers/1/id',
 'childPosts/3/taggedUsers/1/is_verified',
 'childPosts/3/taggedUsers/1/profile_pic_url',
 'childPosts/3/taggedUsers/1/username',
 'childPosts/3/taggedUsers/2/full_name',
 'childPosts/3/taggedUsers/2/id',
 'childPosts/3/taggedUsers/2/is_verified',
 'childPosts/3/taggedUsers/2/profile_pic_url',
 'childPosts/3/taggedUsers/2/username',
 'childPosts/3/taggedUsers/3/full_name',
 'childPosts/3/taggedUsers/3/id',
 'childPosts/3/taggedUsers/3/is_verified',
 'childPosts/3/taggedUsers/3/profile_pic_url',
 'childPosts/3/taggedUsers/3/username',
 'childPosts/3/timestamp',
 'childPosts/3/type',
 'childPosts/3/url',
 'childPosts/4/alt',
 'childPosts/4/caption',
 'childPosts/4/commentsCount',
 'childPosts/4/dimensionsHeight',
 'childPosts/4/dimensionsWidth',
 'childPosts/4/displayUrl',
 'childPosts/4/firstComment',
 'childPosts/4/id',
 'childPosts/4/likesCount',
 'childPosts/4/ownerId',
 'childPosts/4/shortCode',
 'childPosts/4/taggedUsers/0/full_name',
 'childPosts/4/taggedUsers/0/id',
 'childPosts/4/taggedUsers/0/is_verified',
 'childPosts/4/taggedUsers/0/profile_pic_url',
 'childPosts/4/taggedUsers/0/username',
 'childPosts/4/taggedUsers/1/full_name',
 'childPosts/4/taggedUsers/1/id',
 'childPosts/4/taggedUsers/1/is_verified',
 'childPosts/4/taggedUsers/1/profile_pic_url',
 'childPosts/4/taggedUsers/1/username',
 'childPosts/4/taggedUsers/2/full_name',
 'childPosts/4/taggedUsers/2/id',
 'childPosts/4/taggedUsers/2/is_verified',
 'childPosts/4/taggedUsers/2/profile_pic_url',
 'childPosts/4/taggedUsers/2/username',
 'childPosts/4/taggedUsers/3/full_name',
 'childPosts/4/taggedUsers/3/id',
 'childPosts/4/taggedUsers/3/is_verified',
 'childPosts/4/taggedUsers/3/profile_pic_url',
 'childPosts/4/taggedUsers/3/username',
 'childPosts/4/timestamp',
 'childPosts/4/type',
 'childPosts/4/url',
 'childPosts/5/alt',
 'childPosts/5/caption',
 'childPosts/5/commentsCount',
 'childPosts/5/dimensionsHeight',
 'childPosts/5/dimensionsWidth',
 'childPosts/5/displayUrl',
 'childPosts/5/firstComment',
 'childPosts/5/id',
 'childPosts/5/likesCount',
 'childPosts/5/ownerId',
 'childPosts/5/shortCode',
 'childPosts/5/taggedUsers/0/full_name',
 'childPosts/5/taggedUsers/0/id',
 'childPosts/5/taggedUsers/0/is_verified',
 'childPosts/5/taggedUsers/0/profile_pic_url',
 'childPosts/5/taggedUsers/0/username',
 'childPosts/5/taggedUsers/1/full_name',
 'childPosts/5/taggedUsers/1/id',
 'childPosts/5/taggedUsers/1/is_verified',
 'childPosts/5/taggedUsers/1/profile_pic_url',
 'childPosts/5/taggedUsers/1/username',
 'childPosts/5/taggedUsers/2/full_name',
 'childPosts/5/taggedUsers/2/id',
 'childPosts/5/taggedUsers/2/is_verified',
 'childPosts/5/taggedUsers/2/profile_pic_url',
 'childPosts/5/taggedUsers/2/username',
 'childPosts/5/taggedUsers/3/full_name',
 'childPosts/5/taggedUsers/3/id',
 'childPosts/5/taggedUsers/3/is_verified',
 'childPosts/5/taggedUsers/3/profile_pic_url',
 'childPosts/5/taggedUsers/3/username',
 'childPosts/5/timestamp',
 'childPosts/5/type',
 'childPosts/5/url',
 'childPosts/6/alt',
 'childPosts/6/caption',
 'childPosts/6/commentsCount',
 'childPosts/6/dimensionsHeight',
 'childPosts/6/dimensionsWidth',
 'childPosts/6/displayUrl',
 'childPosts/6/firstComment',
 'childPosts/6/id',
 'childPosts/6/likesCount',
 'childPosts/6/ownerId',
 'childPosts/6/shortCode',
 'childPosts/6/taggedUsers/0/full_name',
 'childPosts/6/taggedUsers/0/id',
 'childPosts/6/taggedUsers/0/is_verified',
 'childPosts/6/taggedUsers/0/profile_pic_url',
 'childPosts/6/taggedUsers/0/username',
 'childPosts/6/taggedUsers/1/full_name',
 'childPosts/6/taggedUsers/1/id',
 'childPosts/6/taggedUsers/1/is_verified',
 'childPosts/6/taggedUsers/1/profile_pic_url',
 'childPosts/6/taggedUsers/1/username',
 'childPosts/6/taggedUsers/2/full_name',
 'childPosts/6/taggedUsers/2/id',
 'childPosts/6/taggedUsers/2/is_verified',
 'childPosts/6/taggedUsers/2/profile_pic_url',
 'childPosts/6/taggedUsers/2/username',
 'childPosts/6/taggedUsers/3/full_name',
 'childPosts/6/taggedUsers/3/id',
 'childPosts/6/taggedUsers/3/is_verified',
 'childPosts/6/taggedUsers/3/profile_pic_url',
 'childPosts/6/taggedUsers/3/username',
 'childPosts/6/timestamp',
 'childPosts/6/type',
 'childPosts/6/url',
 'childPosts/7/alt',
 'childPosts/7/caption',
 'childPosts/7/commentsCount',
 'childPosts/7/dimensionsHeight',
 'childPosts/7/dimensionsWidth',
 'childPosts/7/displayUrl',
 'childPosts/7/firstComment',
 'childPosts/7/id',
 'childPosts/7/likesCount',
 'childPosts/7/ownerId',
 'childPosts/7/shortCode',
 'childPosts/7/taggedUsers/0/full_name',
 'childPosts/7/taggedUsers/0/id',
 'childPosts/7/taggedUsers/0/is_verified',
 'childPosts/7/taggedUsers/0/profile_pic_url',
 'childPosts/7/taggedUsers/0/username',
 'childPosts/7/taggedUsers/1/full_name',
 'childPosts/7/taggedUsers/1/id',
 'childPosts/7/taggedUsers/1/is_verified',
 'childPosts/7/taggedUsers/1/profile_pic_url',
 'childPosts/7/taggedUsers/1/username',
 'childPosts/7/taggedUsers/2/full_name',
 'childPosts/7/taggedUsers/2/id',
 'childPosts/7/taggedUsers/2/is_verified',
 'childPosts/7/taggedUsers/2/profile_pic_url',
 'childPosts/7/taggedUsers/2/username',
 'childPosts/7/taggedUsers/3/full_name',
 'childPosts/7/taggedUsers/3/id',
 'childPosts/7/taggedUsers/3/is_verified',
 'childPosts/7/taggedUsers/3/profile_pic_url',
 'childPosts/7/taggedUsers/3/username',
 'childPosts/7/timestamp',
 'childPosts/7/type',
 'childPosts/7/url',
 'childPosts/8/alt',
 'childPosts/8/caption',
 'childPosts/8/commentsCount',
 'childPosts/8/dimensionsHeight',
 'childPosts/8/dimensionsWidth',
 'childPosts/8/displayUrl',
 'childPosts/8/firstComment',
 'childPosts/8/id',
 'childPosts/8/likesCount',
 'childPosts/8/ownerId',
 'childPosts/8/shortCode',
 'childPosts/8/taggedUsers/0/full_name',
 'childPosts/8/taggedUsers/0/id',
 'childPosts/8/taggedUsers/0/is_verified',
 'childPosts/8/taggedUsers/0/profile_pic_url',
 'childPosts/8/taggedUsers/0/username',
 'childPosts/8/taggedUsers/1/full_name',
 'childPosts/8/taggedUsers/1/id',
 'childPosts/8/taggedUsers/1/is_verified',
 'childPosts/8/taggedUsers/1/profile_pic_url',
 'childPosts/8/taggedUsers/1/username',
 'childPosts/8/taggedUsers/2/full_name',
 'childPosts/8/taggedUsers/2/id',
 'childPosts/8/taggedUsers/2/is_verified',
 'childPosts/8/taggedUsers/2/profile_pic_url',
 'childPosts/8/taggedUsers/2/username',
 'childPosts/8/taggedUsers/3/full_name',
 'childPosts/8/taggedUsers/3/id',
 'childPosts/8/taggedUsers/3/is_verified',
 'childPosts/8/taggedUsers/3/profile_pic_url',
 'childPosts/8/taggedUsers/3/username',
 'childPosts/8/timestamp',
 'childPosts/8/type',
 'childPosts/8/url',
 'childPosts/9/alt',
 'childPosts/9/caption',
 'childPosts/9/commentsCount',
 'childPosts/9/dimensionsHeight',
 'childPosts/9/dimensionsWidth',
 'childPosts/9/displayUrl',
 'childPosts/9/firstComment',
 'childPosts/9/id',
 'childPosts/9/likesCount',
 'childPosts/9/ownerId',
 'childPosts/9/shortCode',
 'childPosts/9/taggedUsers/0/full_name',
 'childPosts/9/taggedUsers/0/id',
 'childPosts/9/taggedUsers/0/is_verified',
 'childPosts/9/taggedUsers/0/profile_pic_url',
 'childPosts/9/taggedUsers/0/username',
 'childPosts/9/taggedUsers/1/full_name',
 'childPosts/9/taggedUsers/1/id',
 'childPosts/9/taggedUsers/1/is_verified',
 'childPosts/9/taggedUsers/1/profile_pic_url',
 'childPosts/9/taggedUsers/1/username',
 'childPosts/9/taggedUsers/2/full_name',
 'childPosts/9/taggedUsers/2/id',
 'childPosts/9/taggedUsers/2/is_verified',
 'childPosts/9/taggedUsers/2/profile_pic_url',
 'childPosts/9/taggedUsers/2/username',
 'childPosts/9/taggedUsers/3/full_name',
 'childPosts/9/taggedUsers/3/id',
 'childPosts/9/taggedUsers/3/is_verified',
 'childPosts/9/taggedUsers/3/profile_pic_url',
 'childPosts/9/taggedUsers/3/username',
 'childPosts/9/timestamp',
 'childPosts/9/type',
 'childPosts/9/url',
 'childPosts/10/alt',
 'childPosts/10/caption',
 'childPosts/10/commentsCount',
 'childPosts/10/dimensionsHeight',
 'childPosts/10/dimensionsWidth',
 'childPosts/10/displayUrl',
 'childPosts/10/firstComment',
 'childPosts/10/id',
 'childPosts/10/likesCount',
 'childPosts/10/ownerId',
 'childPosts/10/shortCode',
 'childPosts/10/taggedUsers/0/full_name',
 'childPosts/10/taggedUsers/0/id',
 'childPosts/10/taggedUsers/0/is_verified',
 'childPosts/10/taggedUsers/0/profile_pic_url',
 'childPosts/10/taggedUsers/0/username',
 'childPosts/10/taggedUsers/1/full_name',
 'childPosts/10/taggedUsers/1/id',
 'childPosts/10/taggedUsers/1/is_verified',
 'childPosts/10/taggedUsers/1/profile_pic_url',
 'childPosts/10/taggedUsers/1/username',
 'childPosts/10/taggedUsers/2/full_name',
 'childPosts/10/taggedUsers/2/id',
 'childPosts/10/taggedUsers/2/is_verified',
 'childPosts/10/taggedUsers/2/profile_pic_url',
 'childPosts/10/taggedUsers/2/username',
 'childPosts/10/taggedUsers/3/full_name',
 'childPosts/10/taggedUsers/3/id',
 'childPosts/10/taggedUsers/3/is_verified',
 'childPosts/10/taggedUsers/3/profile_pic_url',
 'childPosts/10/taggedUsers/3/username',
 'childPosts/10/timestamp',
 'childPosts/10/type',
 'childPosts/10/url',
 'commentsCount',
 'dimensionsHeight',
 'dimensionsWidth',
 'displayUrl',
 'firstComment',
 'hashtags/0',
 'hashtags/1',
 'hashtags/2',
 'hashtags/3',
 'hashtags/4',
 'hashtags/5',
 'hashtags/6',
 'hashtags/7',
 'hashtags/8',
 'hashtags/9',
 'hashtags/10',
 'hashtags/11',
 'hashtags/12',
 'hashtags/13',
 'hashtags/14',
 'hashtags/15',
 'hashtags/16',
 'hashtags/17',
 'hashtags/18',
 'hashtags/19',
 'hashtags/20',
 'hashtags/21',
 'hashtags/22',
 'hashtags/23',
 'hashtags/24',
 'hashtags/25',
 'hashtags/26',
 'hashtags/27',
 'hashtags/28',
 'id',
 'images/0',
 'images/1',
 'images/2',
 'images/3',
 'images/4',
 'images/5',
 'images/6',
 'images/7',
 'images/8',
 'images/9',
 'images/10',
 'inputUrl',
 'isCommentsDisabled',
 'latestComments/0/id',
 'latestComments/0/likesCount',
 'latestComments/0/owner/id',
 'latestComments/0/owner/is_verified',
 'latestComments/0/owner/profile_pic_url',
 'latestComments/0/owner/username',
 'latestComments/0/ownerProfilePicUrl',
 'latestComments/0/ownerUsername',
 'latestComments/0/replies/0/id',
 'latestComments/0/replies/0/likesCount',
 'latestComments/0/replies/0/owner/id',
 'latestComments/0/replies/0/owner/is_verified',
 'latestComments/0/replies/0/owner/profile_pic_url',
 'latestComments/0/replies/0/owner/username',
 'latestComments/0/replies/0/ownerProfilePicUrl',
 'latestComments/0/replies/0/ownerUsername',
 'latestComments/0/replies/0/repliesCount',
 'latestComments/0/replies/0/text',
 'latestComments/0/replies/0/timestamp',
 'latestComments/0/repliesCount',
 'latestComments/0/text',
 'latestComments/0/timestamp',
 'latestComments/1/id',
 'latestComments/1/likesCount',
 'latestComments/1/owner/id',
 'latestComments/1/owner/is_verified',
 'latestComments/1/owner/profile_pic_url',
 'latestComments/1/owner/username',
 'latestComments/1/ownerProfilePicUrl',
 'latestComments/1/ownerUsername',
 'latestComments/1/replies/0/id',
 'latestComments/1/replies/0/likesCount',
 'latestComments/1/replies/0/owner/id',
 'latestComments/1/replies/0/owner/is_verified',
 'latestComments/1/replies/0/owner/profile_pic_url',
 'latestComments/1/replies/0/owner/username',
 'latestComments/1/replies/0/ownerProfilePicUrl',
 'latestComments/1/replies/0/ownerUsername',
 'latestComments/1/replies/0/repliesCount',
 'latestComments/1/replies/0/text',
 'latestComments/1/replies/0/timestamp',
 'latestComments/1/repliesCount',
 'latestComments/1/text',
 'latestComments/1/timestamp',
 'latestComments/2/id',
 'latestComments/2/likesCount',
 'latestComments/2/owner/id',
 'latestComments/2/owner/is_verified',
 'latestComments/2/owner/profile_pic_url',
 'latestComments/2/owner/username',
 'latestComments/2/ownerProfilePicUrl',
 'latestComments/2/ownerUsername',
 'latestComments/2/replies/0/id',
 'latestComments/2/replies/0/likesCount',
 'latestComments/2/replies/0/owner/id',
 'latestComments/2/replies/0/owner/is_verified',
 'latestComments/2/replies/0/owner/profile_pic_url',
 'latestComments/2/replies/0/owner/username',
 'latestComments/2/replies/0/ownerProfilePicUrl',
 'latestComments/2/replies/0/ownerUsername',
 'latestComments/2/replies/0/repliesCount',
 'latestComments/2/replies/0/text',
 'latestComments/2/replies/0/timestamp',
 'latestComments/2/repliesCount',
 'latestComments/2/text',
 'latestComments/2/timestamp',
 'latestComments/3/id',
 'latestComments/3/likesCount',
 'latestComments/3/owner/id',
 'latestComments/3/owner/is_verified',
 'latestComments/3/owner/profile_pic_url',
 'latestComments/3/owner/username',
 'latestComments/3/ownerProfilePicUrl',
 'latestComments/3/ownerUsername',
 'latestComments/3/replies/0/id',
 'latestComments/3/replies/0/likesCount',
 'latestComments/3/replies/0/owner/id',
 'latestComments/3/replies/0/owner/is_verified',
 'latestComments/3/replies/0/owner/profile_pic_url',
 'latestComments/3/replies/0/owner/username',
 'latestComments/3/replies/0/ownerProfilePicUrl',
 'latestComments/3/replies/0/ownerUsername',
 'latestComments/3/replies/0/repliesCount',
 'latestComments/3/replies/0/text',
 'latestComments/3/replies/0/timestamp',
 'latestComments/3/repliesCount',
 'latestComments/3/text',
 'latestComments/3/timestamp',
 'latestComments/4/id',
 'latestComments/4/likesCount',
 'latestComments/4/owner/id',
 'latestComments/4/owner/is_verified',
 'latestComments/4/owner/profile_pic_url',
 'latestComments/4/owner/username',
 'latestComments/4/ownerProfilePicUrl',
 'latestComments/4/ownerUsername',
 'latestComments/4/replies/0/id',
 'latestComments/4/replies/0/likesCount',
 'latestComments/4/replies/0/owner/id',
 'latestComments/4/replies/0/owner/is_verified',
 'latestComments/4/replies/0/owner/profile_pic_url',
 'latestComments/4/replies/0/owner/username',
 'latestComments/4/replies/0/ownerProfilePicUrl',
 'latestComments/4/replies/0/ownerUsername',
 'latestComments/4/replies/0/repliesCount',
 'latestComments/4/replies/0/text',
 'latestComments/4/replies/0/timestamp',
 'latestComments/4/repliesCount',
 'latestComments/4/text',
 'latestComments/4/timestamp',
 'latestComments/5/id',
 'latestComments/5/likesCount',
 'latestComments/5/owner/id',
 'latestComments/5/owner/is_verified',
 'latestComments/5/owner/profile_pic_url',
 'latestComments/5/owner/username',
 'latestComments/5/ownerProfilePicUrl',
 'latestComments/5/ownerUsername',
 'latestComments/5/replies/0/id',
 'latestComments/5/replies/0/likesCount',
 'latestComments/5/replies/0/owner/id',
 'latestComments/5/replies/0/owner/is_verified',
 'latestComments/5/replies/0/owner/profile_pic_url',
 'latestComments/5/replies/0/owner/username',
 'latestComments/5/replies/0/ownerProfilePicUrl',
 'latestComments/5/replies/0/ownerUsername',
 'latestComments/5/replies/0/repliesCount',
 'latestComments/5/replies/0/text',
 'latestComments/5/replies/0/timestamp',
 'latestComments/5/repliesCount',
 'latestComments/5/text',
 'latestComments/5/timestamp',
 'latestComments/6/id',
 'latestComments/6/likesCount',
 'latestComments/6/owner/id',
 'latestComments/6/owner/is_verified',
 'latestComments/6/owner/profile_pic_url',
 'latestComments/6/owner/username',
 'latestComments/6/ownerProfilePicUrl',
 'latestComments/6/ownerUsername',
 'latestComments/6/replies/0/id',
 'latestComments/6/replies/0/likesCount',
 'latestComments/6/replies/0/owner/id',
 'latestComments/6/replies/0/owner/is_verified',
 'latestComments/6/replies/0/owner/profile_pic_url',
 'latestComments/6/replies/0/owner/username',
 'latestComments/6/replies/0/ownerProfilePicUrl',
 'latestComments/6/replies/0/ownerUsername',
 'latestComments/6/replies/0/repliesCount',
 'latestComments/6/replies/0/text',
 'latestComments/6/replies/0/timestamp',
 'latestComments/6/repliesCount',
 'latestComments/6/text',
 'latestComments/6/timestamp',
 'latestComments/7/id',
 'latestComments/7/likesCount',
 'latestComments/7/owner/id',
 'latestComments/7/owner/is_verified',

In [9]:
# dumping all of the unnecessary columns apify gave us. 
# Most of these are just useless for our analysis and 
# some of them have too many nulls and too few unique values to be useful.
keep = [
    'shortCode', 'url', 'type', 'timestamp',
    'likesCount', 'commentsCount',
    'caption',
] + [f'hashtags/{i}' for i in range(11)]

keep = [c for c in keep if c in insta_data.columns]
insta_data = insta_data[keep]
print(insta_data.shape)

(135, 18)

In [10]:
insta_data.head()

,shortCode,url,type,timestamp,likesCount,commentsCount,caption,hashtags/0,hashtags/1,hashtags/2,hashtags/3,hashtags/4,hashtags/5,hashtags/6,hashtags/7,hashtags/8,hashtags/9,hashtags/10
0,DSFIFKpEmJE,https://www.instagram.com/p/DSFIFKpEmJE/,Image,2025-12-10T10:46:36.000Z,88,1,"The Game Awards 2025 is almost here, and it’s ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DWgzWT3krsg,https://www.instagram.com/p/DWgzWT3krsg/,Sidecar,2026-03-30T14:49:45.000Z,126,0,Part 2 of our Hair contribution in @obsidian A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DRKVsCKEjL9,https://www.instagram.com/p/DRKVsCKEjL9/,Image,2025-11-17T14:50:19.000Z,117,0,"Call of Duty: Black Ops 7 is out, and we’re th...",callofduty,callofdutyblackops,callofdutyblackops7,lrz,littleredzombies,NaN,NaN,NaN,NaN,NaN,NaN
3,DWgyRJ5ks-I,https://www.instagram.com/p/DWgyRJ5ks-I/,Sidecar,2026-03-30T14:40:19.000Z,98,0,"We’re excited to share our work on Avowed, our...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DSsTgwHktZh,https://www.instagram.com/p/DSsTgwHktZh/,Sidecar,2025-12-25T15:56:52.000Z,154,0,"As the year winds down, we’re taking a moment ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
print(insta_data.isnull().sum())

shortCode          0
url                0
type               0
timestamp          0
likesCount         0
commentsCount      0
caption            0
hashtags/0        25
hashtags/1        26
hashtags/2        26
hashtags/3        28
hashtags/4        41
hashtags/5        55
hashtags/6        73
hashtags/7        82
hashtags/8        98
hashtags/9       108
hashtags/10      114
dtype: int64

In [12]:
# collapse all hashtag values into a single column
hashtag_cols = [c for c in insta_data.columns if c.startswith('hashtags/')]
insta_data['hashtags'] = insta_data[hashtag_cols].apply(lambda row: ', '.join(row.dropna().astype(str)), axis=1)
insta_data.drop(columns=hashtag_cols, inplace=True)

In [13]:
print(insta_data.shape)
print(insta_data.isnull().sum())

(135, 8)
shortCode        0
url              0
type             0
timestamp        0
likesCount       0
commentsCount    0
caption          0
hashtags         0
dtype: int64

In [14]:
insta_data.head(5)

,shortCode,url,type,timestamp,likesCount,commentsCount,caption,hashtags
0,DSFIFKpEmJE,https://www.instagram.com/p/DSFIFKpEmJE/,Image,2025-12-10T10:46:36.000Z,88,1,"The Game Awards 2025 is almost here, and it’s ...",
1,DWgzWT3krsg,https://www.instagram.com/p/DWgzWT3krsg/,Sidecar,2026-03-30T14:49:45.000Z,126,0,Part 2 of our Hair contribution in @obsidian A...,
2,DRKVsCKEjL9,https://www.instagram.com/p/DRKVsCKEjL9/,Image,2025-11-17T14:50:19.000Z,117,0,"Call of Duty: Black Ops 7 is out, and we’re th...","callofduty, callofdutyblackops, callofdutyblac..."
3,DWgyRJ5ks-I,https://www.instagram.com/p/DWgyRJ5ks-I/,Sidecar,2026-03-30T14:40:19.000Z,98,0,"We’re excited to share our work on Avowed, our...",
4,DSsTgwHktZh,https://www.instagram.com/p/DSsTgwHktZh/,Sidecar,2025-12-25T15:56:52.000Z,154,0,"As the year winds down, we’re taking a moment ...",

In [15]:
insta_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   shortCode      135 non-null    object
 1   url            135 non-null    object
 2   type           135 non-null    object
 3   timestamp      135 non-null    object
 4   likesCount     135 non-null    int64
 5   commentsCount  135 non-null    int64
 6   caption        135 non-null    object
 7   hashtags       135 non-null    object
dtypes: int64(2), object(6)
memory usage: 8.6+ KB

In [16]:
print(insta_data.describe())

        likesCount  commentsCount
count   135.000000     135.000000
mean    207.918519       3.081481
std     149.892601       9.430066
min      44.000000       0.000000
25%     107.500000       0.000000
50%     173.000000       1.000000
75%     261.500000       2.000000
max    1287.000000      93.000000

In [17]:
mean, std = insta_data['likesCount'].mean(), insta_data['likesCount'].std()
print(f"INSTAGRAM\nLikes\nMean: {mean}, Std: {std}")
mean, std = insta_data['commentsCount'].mean(), insta_data['commentsCount'].std()
print(f"Comments\nMean: {mean}, Std: {std}")

INSTAGRAM
Likes
Mean: 207.9185185185185, Std: 149.89260094709263
Comments
Mean: 3.0814814814814815, Std: 9.430066120794963

In [19]:
insta_data.to_excel(common_path / 'Data' / 'cleaned' / 'instagram_clean.xlsx', index=False)
print("Done:", insta_data.shape)

Done: (135, 8)

#### LinkedIn Data

In [20]:
link_data = pd.read_excel(common_path / 'Data' / 'raw' / 'dataset_linkedin-post_2026-05-13_14-50-21-786.xlsx')

In [21]:
link_data.shape

(53, 1389)

In [22]:
print(link_data.isnull().sum())

activityDescription            51
activityOfCompany/active       51
activityOfCompany/entityUrn    51
activityOfCompany/logoUrl      51
activityOfCompany/name         51
                               ..
text                            0
timeSincePosted                 0
type                            0
url                             0
urn                             0
Length: 1389, dtype: int64

In [23]:
list(link_data.columns)

['activityDescription',
 'activityOfCompany/active',
 'activityOfCompany/entityUrn',
 'activityOfCompany/logoUrl',
 'activityOfCompany/name',
 'activityOfCompany/showcase',
 'activityOfCompany/trackingId',
 'activityOfCompany/universalName',
 'allowedCommentersScope',
 'attributes/0/company/active',
 'attributes/0/company/entityUrn',
 'attributes/0/company/logoUrl',
 'attributes/0/company/name',
 'attributes/0/company/showcase',
 'attributes/0/company/trackingId',
 'attributes/0/company/universalName',
 'attributes/0/length',
 'attributes/0/profile/backgroundImage',
 'attributes/0/profile/firstName',
 'attributes/0/profile/id',
 'attributes/0/profile/lastName',
 'attributes/0/profile/occupation',
 'attributes/0/profile/picture',
 'attributes/0/profile/profileId',
 'attributes/0/profile/publicId',
 'attributes/0/profile/trackingId',
 'attributes/0/start',
 'attributes/0/type',
 'attributes/1/company/active',
 'attributes/1/company/entityUrn',
 'attributes/1/company/logoUrl',
 'attributes/1/company/name',
 'attributes/1/company/showcase',
 'attributes/1/company/trackingId',
 'attributes/1/company/universalName',
 'attributes/1/length',
 'attributes/1/profile/backgroundImage',
 'attributes/1/profile/firstName',
 'attributes/1/profile/id',
 'attributes/1/profile/lastName',
 'attributes/1/profile/occupation',
 'attributes/1/profile/picture',
 'attributes/1/profile/profileId',
 'attributes/1/profile/publicId',
 'attributes/1/profile/trackingId',
 'attributes/1/start',
 'attributes/1/type',
 'attributes/2/company/active',
 'attributes/2/company/entityUrn',
 'attributes/2/company/logoUrl',
 'attributes/2/company/name',
 'attributes/2/company/showcase',
 'attributes/2/company/trackingId',
 'attributes/2/company/universalName',
 'attributes/2/length',
 'attributes/2/profile/backgroundImage',
 'attributes/2/profile/firstName',
 'attributes/2/profile/id',
 'attributes/2/profile/lastName',
 'attributes/2/profile/occupation',
 'attributes/2/profile/picture',
 'attributes/2/profile/profileId',
 'attributes/2/profile/publicId',
 'attributes/2/profile/trackingId',
 'attributes/2/start',
 'attributes/2/type',
 'author/active',
 'author/entityUrn',
 'author/logoUrl',
 'author/name',
 'author/showcase',
 'author/trackingId',
 'author/universalName',
 'authorFollowersCount',
 'authorName',
 'authorProfileId',
 'authorProfilePicture',
 'authorProfileUrl',
 'authorType',
 'authorUrn',
 'canPostComments',
 'canReact',
 'canShare',
 'commentingDisabled',
 'comments/0/author/backgroundImage',
 'comments/0/author/distance',
 'comments/0/author/firstName',
 'comments/0/author/id',
 'comments/0/author/lastName',
 'comments/0/author/occupation',
 'comments/0/author/picture',
 'comments/0/author/profileId',
 'comments/0/author/publicId',
 'comments/0/author/trackingId',
 'comments/0/entities/0/company/active',
 'comments/0/entities/0/company/entityUrn',
 'comments/0/entities/0/company/logoUrl',
 'comments/0/entities/0/company/name',
 'comments/0/entities/0/company/showcase',
 'comments/0/entities/0/company/trackingId',
 'comments/0/entities/0/company/universalName',
 'comments/0/entities/0/length',
 'comments/0/entities/0/profile/backgroundImage',
 'comments/0/entities/0/profile/firstName',
 'comments/0/entities/0/profile/id',
 'comments/0/entities/0/profile/lastName',
 'comments/0/entities/0/profile/occupation',
 'comments/0/entities/0/profile/picture',
 'comments/0/entities/0/profile/profileId',
 'comments/0/entities/0/profile/publicId',
 'comments/0/entities/0/profile/trackingId',
 'comments/0/entities/0/start',
 'comments/0/entities/0/type',
 'comments/0/entities/1/company/active',
 'comments/0/entities/1/company/entityUrn',
 'comments/0/entities/1/company/logoUrl',
 'comments/0/entities/1/company/name',
 'comments/0/entities/1/company/showcase',
 'comments/0/entities/1/company/trackingId',
 'comments/0/entities/1/company/universalName',
 'comments/0/entities/1/length',
 'comments/0/entities/1/profile/backgroundImage',
 'comments/0/entities/1/profile/firstName',
 'comments/0/entities/1/profile/id',
 'comments/0/entities/1/profile/lastName',
 'comments/0/entities/1/profile/occupation',
 'comments/0/entities/1/profile/picture',
 'comments/0/entities/1/profile/profileId',
 'comments/0/entities/1/profile/publicId',
 'comments/0/entities/1/profile/trackingId',
 'comments/0/entities/1/start',
 'comments/0/entities/1/type',
 'comments/0/link',
 'comments/0/originalLanguage',
 'comments/0/pinned',
 'comments/0/text',
 'comments/0/time',
 'comments/1/author/backgroundImage',
 'comments/1/author/distance',
 'comments/1/author/firstName',
 'comments/1/author/id',
 'comments/1/author/lastName',
 'comments/1/author/occupation',
 'comments/1/author/picture',
 'comments/1/author/profileId',
 'comments/1/author/publicId',
 'comments/1/author/trackingId',
 'comments/1/entities/0/company/active',
 'comments/1/entities/0/company/entityUrn',
 'comments/1/entities/0/company/logoUrl',
 'comments/1/entities/0/company/name',
 'comments/1/entities/0/company/showcase',
 'comments/1/entities/0/company/trackingId',
 'comments/1/entities/0/company/universalName',
 'comments/1/entities/0/length',
 'comments/1/entities/0/profile/backgroundImage',
 'comments/1/entities/0/profile/firstName',
 'comments/1/entities/0/profile/id',
 'comments/1/entities/0/profile/lastName',
 'comments/1/entities/0/profile/occupation',
 'comments/1/entities/0/profile/picture',
 'comments/1/entities/0/profile/profileId',
 'comments/1/entities/0/profile/publicId',
 'comments/1/entities/0/profile/trackingId',
 'comments/1/entities/0/start',
 'comments/1/entities/0/type',
 'comments/1/entities/1/company/active',
 'comments/1/entities/1/company/entityUrn',
 'comments/1/entities/1/company/logoUrl',
 'comments/1/entities/1/company/name',
 'comments/1/entities/1/company/showcase',
 'comments/1/entities/1/company/trackingId',
 'comments/1/entities/1/company/universalName',
 'comments/1/entities/1/length',
 'comments/1/entities/1/profile/backgroundImage',
 'comments/1/entities/1/profile/firstName',
 'comments/1/entities/1/profile/id',
 'comments/1/entities/1/profile/lastName',
 'comments/1/entities/1/profile/occupation',
 'comments/1/entities/1/profile/picture',
 'comments/1/entities/1/profile/profileId',
 'comments/1/entities/1/profile/publicId',
 'comments/1/entities/1/profile/trackingId',
 'comments/1/entities/1/start',
 'comments/1/entities/1/type',
 'comments/1/link',
 'comments/1/originalLanguage',
 'comments/1/pinned',
 'comments/1/text',
 'comments/1/time',
 'comments/2/author/backgroundImage',
 'comments/2/author/distance',
 'comments/2/author/firstName',
 'comments/2/author/id',
 'comments/2/author/lastName',
 'comments/2/author/occupation',
 'comments/2/author/picture',
 'comments/2/author/profileId',
 'comments/2/author/publicId',
 'comments/2/author/trackingId',
 'comments/2/entities/0/company/active',
 'comments/2/entities/0/company/entityUrn',
 'comments/2/entities/0/company/logoUrl',
 'comments/2/entities/0/company/name',
 'comments/2/entities/0/company/showcase',
 'comments/2/entities/0/company/trackingId',
 'comments/2/entities/0/company/universalName',
 'comments/2/entities/0/length',
 'comments/2/entities/0/profile/backgroundImage',
 'comments/2/entities/0/profile/firstName',
 'comments/2/entities/0/profile/id',
 'comments/2/entities/0/profile/lastName',
 'comments/2/entities/0/profile/occupation',
 'comments/2/entities/0/profile/picture',
 'comments/2/entities/0/profile/profileId',
 'comments/2/entities/0/profile/publicId',
 'comments/2/entities/0/profile/trackingId',
 'comments/2/entities/0/start',
 'comments/2/entities/0/type',
 'comments/2/entities/1/company/active',
 'comments/2/entities/1/company/entityUrn',
 'comments/2/entities/1/company/logoUrl',
 'comments/2/entities/1/company/name',
 'comments/2/entities/1/company/showcase',
 'comments/2/entities/1/company/trackingId',
 'comments/2/entities/1/company/universalName',
 'comments/2/entities/1/length',
 'comments/2/entities/1/profile/backgroundImage',
 'comments/2/entities/1/profile/firstName',
 'comments/2/entities/1/profile/id',
 'comments/2/entities/1/profile/lastName',
 'comments/2/entities/1/profile/occupation',
 'comments/2/entities/1/profile/picture',
 'comments/2/entities/1/profile/profileId',
 'comments/2/entities/1/profile/publicId',
 'comments/2/entities/1/profile/trackingId',
 'comments/2/entities/1/start',
 'comments/2/entities/1/type',
 'comments/2/link',
 'comments/2/originalLanguage',
 'comments/2/pinned',
 'comments/2/text',
 'comments/2/time',
 'comments/3/author/backgroundImage',
 'comments/3/author/distance',
 'comments/3/author/firstName',
 'comments/3/author/id',
 'comments/3/author/lastName',
 'comments/3/author/occupation',
 'comments/3/author/picture',
 'comments/3/author/profileId',
 'comments/3/author/publicId',
 'comments/3/author/trackingId',
 'comments/3/entities/0/company/active',
 'comments/3/entities/0/company/entityUrn',
 'comments/3/entities/0/company/logoUrl',
 'comments/3/entities/0/company/name',
 'comments/3/entities/0/company/showcase',
 'comments/3/entities/0/company/trackingId',
 'comments/3/entities/0/company/universalName',
 'comments/3/entities/0/length',
 'comments/3/entities/0/profile/backgroundImage',
 'comments/3/entities/0/profile/firstName',
 'comments/3/entities/0/profile/id',
 'comments/3/entities/0/profile/lastName',
 'comments/3/entities/0/profile/occupation',
 'comments/3/entities/0/profile/picture',
 'comments/3/entities/0/profile/profileId',
 'comments/3/entities/0/profile/publicId',
 'comments/3/entities/0/profile/trackingId',
 'comments/3/entities/0/start',
 'comments/3/entities/0/type',
 'comments/3/entities/1/company/active',
 'comments/3/entities/1/company/entityUrn',
 'comments/3/entities/1/company/logoUrl',
 'comments/3/entities/1/company/name',
 'comments/3/entities/1/company/showcase',
 'comments/3/entities/1/company/trackingId',
 'comments/3/entities/1/company/universalName',
 'comments/3/entities/1/length',
 'comments/3/entities/1/profile/backgroundImage',
 'comments/3/entities/1/profile/firstName',
 'comments/3/entities/1/profile/id',
 'comments/3/entities/1/profile/lastName',
 'comments/3/entities/1/profile/occupation',
 'comments/3/entities/1/profile/picture',
 'comments/3/entities/1/profile/profileId',
 'comments/3/entities/1/profile/publicId',
 'comments/3/entities/1/profile/trackingId',
 'comments/3/entities/1/start',
 'comments/3/entities/1/type',
 'comments/3/link',
 'comments/3/originalLanguage',
 'comments/3/pinned',
 'comments/3/text',
 'comments/3/time',
 'comments/4/author/backgroundImage',
 'comments/4/author/distance',
 'comments/4/author/firstName',
 'comments/4/author/id',
 'comments/4/author/lastName',
 'comments/4/author/occupation',
 'comments/4/author/picture',
 'comments/4/author/profileId',
 'comments/4/author/publicId',
 'comments/4/author/trackingId',
 'comments/4/entities/0/company/active',
 'comments/4/entities/0/company/entityUrn',
 'comments/4/entities/0/company/logoUrl',
 'comments/4/entities/0/company/name',
 'comments/4/entities/0/company/showcase',
 'comments/4/entities/0/company/trackingId',
 'comments/4/entities/0/company/universalName',
 'comments/4/entities/0/length',
 'comments/4/entities/0/profile/backgroundImage',
 'comments/4/entities/0/profile/firstName',
 'comments/4/entities/0/profile/id',
 'comments/4/entities/0/profile/lastName',
 'comments/4/entities/0/profile/occupation',
 'comments/4/entities/0/profile/picture',
 'comments/4/entities/0/profile/profileId',
 'comments/4/entities/0/profile/publicId',
 'comments/4/entities/0/profile/trackingId',
 'comments/4/entities/0/start',
 'comments/4/entities/0/type',
 'comments/4/entities/1/company/active',
 'comments/4/entities/1/company/entityUrn',
 'comments/4/entities/1/company/logoUrl',
 'comments/4/entities/1/company/name',
 'comments/4/entities/1/company/showcase',
 'comments/4/entities/1/company/trackingId',
 'comments/4/entities/1/company/universalName',
 'comments/4/entities/1/length',
 'comments/4/entities/1/profile/backgroundImage',
 'comments/4/entities/1/profile/firstName',
 'comments/4/entities/1/profile/id',
 'comments/4/entities/1/profile/lastName',
 'comments/4/entities/1/profile/occupation',
 'comments/4/entities/1/profile/picture',
 'comments/4/entities/1/profile/profileId',
 'comments/4/entities/1/profile/publicId',
 'comments/4/entities/1/profile/trackingId',
 'comments/4/entities/1/start',
 'comments/4/entities/1/type',
 'comments/4/link',
 'comments/4/originalLanguage',
 'comments/4/pinned',
 'comments/4/text',
 'comments/4/time',
 'comments/5/author/backgroundImage',
 'comments/5/author/distance',
 'comments/5/author/firstName',
 'comments/5/author/id',
 'comments/5/author/lastName',
 'comments/5/author/occupation',
 'comments/5/author/picture',
 'comments/5/author/profileId',
 'comments/5/author/publicId',
 'comments/5/author/trackingId',
 'comments/5/entities/0/company/active',
 'comments/5/entities/0/company/entityUrn',
 'comments/5/entities/0/company/logoUrl',
 'comments/5/entities/0/company/name',
 'comments/5/entities/0/company/showcase',
 'comments/5/entities/0/company/trackingId',
 'comments/5/entities/0/company/universalName',
 'comments/5/entities/0/length',
 'comments/5/entities/0/profile/backgroundImage',
 'comments/5/entities/0/profile/firstName',
 'comments/5/entities/0/profile/id',
 'comments/5/entities/0/profile/lastName',
 'comments/5/entities/0/profile/occupation',
 'comments/5/entities/0/profile/picture',
 'comments/5/entities/0/profile/profileId',
 'comments/5/entities/0/profile/publicId',
 'comments/5/entities/0/profile/trackingId',
 'comments/5/entities/0/start',
 'comments/5/entities/0/type',
 'comments/5/entities/1/company/active',
 'comments/5/entities/1/company/entityUrn',
 'comments/5/entities/1/company/logoUrl',
 'comments/5/entities/1/company/name',
 'comments/5/entities/1/company/showcase',
 'comments/5/entities/1/company/trackingId',
 'comments/5/entities/1/company/universalName',
 'comments/5/entities/1/length',
 'comments/5/entities/1/profile/backgroundImage',
 'comments/5/entities/1/profile/firstName',
 'comments/5/entities/1/profile/id',
 'comments/5/entities/1/profile/lastName',
 'comments/5/entities/1/profile/occupation',
 'comments/5/entities/1/profile/picture',
 'comments/5/entities/1/profile/profileId',
 'comments/5/entities/1/profile/publicId',
 'comments/5/entities/1/profile/trackingId',
 'comments/5/entities/1/start',
 'comments/5/entities/1/type',
 'comments/5/link',
 'comments/5/originalLanguage',
 'comments/5/pinned',
 'comments/5/text',
 'comments/5/time',
 'comments/6/author/backgroundImage',
 'comments/6/author/distance',
 'comments/6/author/firstName',
 'comments/6/author/id',
 'comments/6/author/lastName',
 'comments/6/author/occupation',
 'comments/6/author/picture',
 'comments/6/author/profileId',
 'comments/6/author/publicId',
 'comments/6/author/trackingId',
 'comments/6/entities/0/company/active',
 'comments/6/entities/0/company/entityUrn',
 'comments/6/entities/0/company/logoUrl',
 'comments/6/entities/0/company/name',
 'comments/6/entities/0/company/showcase',
 'comments/6/entities/0/company/trackingId',
 'comments/6/entities/0/company/universalName',
 'comments/6/entities/0/length',
 'comments/6/entities/0/profile/backgroundImage',
 'comments/6/entities/0/profile/firstName',
 'comments/6/entities/0/profile/id',
 'comments/6/entities/0/profile/lastName',
 'comments/6/entities/0/profile/occupation',
 'comments/6/entities/0/profile/picture',
 'comments/6/entities/0/profile/profileId',
 'comments/6/entities/0/profile/publicId',
 'comments/6/entities/0/profile/trackingId',
 'comments/6/entities/0/start',
 'comments/6/entities/0/type',
 'comments/6/entities/1/company/active',
 'comments/6/entities/1/company/entityUrn',
 'comments/6/entities/1/company/logoUrl',
 'comments/6/entities/1/company/name',
 'comments/6/entities/1/company/showcase',
 'comments/6/entities/1/company/trackingId',
 'comments/6/entities/1/company/universalName',
 'comments/6/entities/1/length',
 'comments/6/entities/1/profile/backgroundImage',
 'comments/6/entities/1/profile/firstName',
 'comments/6/entities/1/profile/id',
 'comments/6/entities/1/profile/lastName',
 'comments/6/entities/1/profile/occupation',
 'comments/6/entities/1/profile/picture',
 'comments/6/entities/1/profile/profileId',
 'comments/6/entities/1/profile/publicId',
 'comments/6/entities/1/profile/trackingId',
 'comments/6/entities/1/start',
 'comments/6/entities/1/type',
 'comments/6/link',
 'comments/6/originalLanguage',
 'comments/6/pinned',
 'comments/6/text',
 'comments/6/time',
 'comments/7/author/backgroundImage',
 'comments/7/author/distance',
 'comments/7/author/firstName',
 'comments/7/author/id',
 'comments/7/author/lastName',
 'comments/7/author/occupation',
 'comments/7/author/picture',
 'comments/7/author/profileId',
 'comments/7/author/publicId',
 'comments/7/author/trackingId',
 'comments/7/entities/0/company/active',
 'comments/7/entities/0/company/entityUrn',
 'comments/7/entities/0/company/logoUrl',
 'comments/7/entities/0/company/name',
 'comments/7/entities/0/company/showcase',
 'comments/7/entities/0/company/trackingId',
 'comments/7/entities/0/company/universalName',
 'comments/7/entities/0/length',
 'comments/7/entities/0/profile/backgroundImage',
 'comments/7/entities/0/profile/firstName',
 'comments/7/entities/0/profile/id',
 'comments/7/entities/0/profile/lastName',
 'comments/7/entities/0/profile/occupation',
 'comments/7/entities/0/profile/picture',
 'comments/7/entities/0/profile/profileId',
 'comments/7/entities/0/profile/publicId',
 'comments/7/entities/0/profile/trackingId',
 'comments/7/entities/0/start',
 'comments/7/entities/0/type',
 'comments/7/entities/1/company/active',
 'comments/7/entities/1/company/entityUrn',
 'comments/7/entities/1/company/logoUrl',
 'comments/7/entities/1/company/name',
 'comments/7/entities/1/company/showcase',
 'comments/7/entities/1/company/trackingId',
 'comments/7/entities/1/company/universalName',
 'comments/7/entities/1/length',
 'comments/7/entities/1/profile/backgroundImage',
 'comments/7/entities/1/profile/firstName',
 'comments/7/entities/1/profile/id',
 'comments/7/entities/1/profile/lastName',
 'comments/7/entities/1/profile/occupation',
 'comments/7/entities/1/profile/picture',
 'comments/7/entities/1/profile/profileId',
 'comments/7/entities/1/profile/publicId',
 'comments/7/entities/1/profile/trackingId',
 'comments/7/entities/1/start',
 'comments/7/entities/1/type',
 'comments/7/link',
 'comments/7/originalLanguage',
 'comments/7/pinned',
 'comments/7/text',
 'comments/7/time',
 'comments/8/author/backgroundImage',
 'comments/8/author/distance',
 'comments/8/author/firstName',
 'comments/8/author/id',
 'comments/8/author/lastName',
 'comments/8/author/occupation',
 'comments/8/author/picture',
 'comments/8/author/profileId',
 'comments/8/author/publicId',
 'comments/8/author/trackingId',
 'comments/8/entities/0/company/active',
 'comments/8/entities/0/company/entityUrn',
 'comments/8/entities/0/company/logoUrl',
 'comments/8/entities/0/company/name',
 'comments/8/entities/0/company/showcase',
 'comments/8/entities/0/company/trackingId',
 'comments/8/entities/0/company/universalName',
 'comments/8/entities/0/length',
 'comments/8/entities/0/profile/backgroundImage',
 'comments/8/entities/0/profile/firstName',
 'comments/8/entities/0/profile/id',
 'comments/8/entities/0/profile/lastName',
 'comments/8/entities/0/profile/occupation',
 'comments/8/entities/0/profile/picture',
 'comments/8/entities/0/profile/profileId',
 'comments/8/entities/0/profile/publicId',
 'comments/8/entities/0/profile/trackingId',
 'comments/8/entities/0/start',
 'comments/8/entities/0/type',
 'comments/8/entities/1/company/active',
 'comments/8/entities/1/company/entityUrn',
 'comments/8/entities/1/company/logoUrl',
 'comments/8/entities/1/company/name',
 'comments/8/entities/1/company/showcase',
 'comments/8/entities/1/company/trackingId',
 'comments/8/entities/1/company/universalName',

In [24]:
keep = [
    'url', 'text', 'postedAtISO', 'numLikes', 
    'numComments', 'numShares', 'type', 'document/title'
]
keep = [c for c in keep if c in link_data.columns]
link_data = link_data[keep]
print(link_data.shape)
print(link_data.isnull().sum())

(53, 8)
url                0
text               0
postedAtISO        0
numLikes           0
numComments        0
numShares          0
type               0
document/title    34
dtype: int64

In [25]:
link_data['document/title'].value_counts()

document/title
Split Fiction - Fauna                                    2
Split Fiction - Story Characters Hair                    2
Alan Wake II: The Lake House – FBC Scientist Outfits     1
Split Fiction - Playable & Story Characters Fur          1
Split Fiction - Rader Hair                               1
Split Fiction - Mio Hair                                 1
Split Fiction - Zoe & the Fairy Hair                     1
Alan Wake II: The Lake House - Dr. Diana Marmont Hair    1
Alan Wake II: The Lake House – FBC Hazmat Suit           1
Pax Dei - Blacksmith                                     1
Pax Dei - Doublet & Leather Armor                        1
Pax Dei - Medieval Armor & Tabard                        1
Split Fiction - Ice King Fur                             1
The Outer Worlds 2 - Hair                                1
Avowed - Fauna                                           1
Avowed - Creatures                                       1
Avowed - Hair Contribution                               1
Name: count, dtype: int64

In [26]:
link_data['document/title'] = link_data['document/title'].fillna('Image/Text Post')

In [27]:
link_data.describe()

         numLikes  numComments  numShares
count   53.000000    53.000000  53.000000
mean   121.094340     1.377358   2.113208
std     68.806379     2.956261   3.017006
min     29.000000     0.000000   0.000000
25%     78.000000     0.000000   0.000000
50%    112.000000     0.000000   1.000000
75%    147.000000     2.000000   2.000000
max    379.000000    20.000000  14.000000

In [28]:
link_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   url             53 non-null     object
 1   text            53 non-null     object
 2   postedAtISO     53 non-null     object
 3   numLikes        53 non-null     int64
 4   numComments     53 non-null     int64
 5   numShares       53 non-null     int64
 6   type            53 non-null     object
 7   document/title  53 non-null     object
dtypes: int64(3), object(5)
memory usage: 3.4+ KB

In [29]:
mean, std = link_data['numLikes'].mean(), link_data['numLikes'].std()
print(f"LINKEDIN\nLikes\nMean: {mean}, Std: {std}")
mean, std = link_data['numComments'].mean(), link_data['numComments'].std()
print(f"Comments\nMean: {mean}, Std: {std}")
mean, std = link_data['numShares'].mean(), link_data['numShares'].std()
print(f"Shares\nMean: {mean}, Std: {std}")

LINKEDIN
Likes
Mean: 121.09433962264151, Std: 68.8063794423116
Comments
Mean: 1.3773584905660377, Std: 2.95626072998111
Shares
Mean: 2.1132075471698113, Std: 3.01700550315968

In [30]:
link_data['type'].value_counts()

type
image       29
document    19
text         5
Name: count, dtype: int64

In [32]:
link_data.to_excel(common_path / 'Data' / 'cleaned' / 'linkedin_clean.xlsx', index=False)
print("Done:", link_data.shape)

Done: (53, 8)

#### X Data

In [35]:
tweet_data = pd.read_excel(common_path / 'Data' / 'raw' / 'dataset_twitter-x-data-tweet-scraper-pay-per-result-cheapest_2026-05-13_15-20-30-100.xlsx')

In [36]:
tweet_data.shape

(200, 2000)

In [37]:
keep = [
    'url', 'twitterUrl', 'createdAt',
    'text', 'lang',
    'likeCount', 'replyCount', 'retweetCount', 
    'quoteCount', 'viewCount', 'bookmarkCount',
    'isReply', 'isPinned',
    'entities/hashtags/0/text',
    'entities/hashtags/1/text',
    'entities/hashtags/2/text',
]

keep = [c for c in keep if c in tweet_data.columns]
tweet_data = tweet_data[keep]
print(tweet_data.shape)
print(tweet_data.isnull().sum())

(200, 16)
url                           0
twitterUrl                    0
createdAt                     0
text                          0
lang                          0
likeCount                     0
replyCount                    0
retweetCount                  0
quoteCount                    0
viewCount                     0
bookmarkCount                 0
isReply                       0
isPinned                      0
entities/hashtags/0/text     80
entities/hashtags/1/text    100
entities/hashtags/2/text    180
dtype: int64

In [38]:
htag_cols = [c for c in tweet_data.columns if c.startswith('entities/hashtags')]
tweet_data['hashtags'] = tweet_data[htag_cols].apply(lambda r: ', '.join(r.dropna().astype(str)), axis=1)
tweet_data.drop(columns=htag_cols, inplace=True)

In [39]:
tweet_data.head()

,url,twitterUrl,createdAt,text,lang,likeCount,replyCount,retweetCount,quoteCount,viewCount,bookmarkCount,isReply,isPinned,hashtags
0,https://x.com/LittleRedZombie/status/175269258...,https://twitter.com/LittleRedZombie/status/175...,Wed Jan 31 13:57:29 +0000 2024,Pretty excited to start 2024 with some big new...,en,3,0,0,0,317,0,False,False,
1,https://x.com/LittleRedZombie/status/173921150...,https://twitter.com/LittleRedZombie/status/173...,Mon Dec 25 09:08:29 +0000 2023,"As another year comes to an end, we gathered t...",en,0,0,0,0,251,0,False,False,
2,https://x.com/LittleRedZombie/status/173876711...,https://twitter.com/LittleRedZombie/status/173...,Sun Dec 24 03:42:39 +0000 2023,"Finally, we head to Remedy Entertainment, in F...",en,1,0,0,0,224,0,False,False,"LittleRedZombies, RemedyEntertainment"
3,https://x.com/LittleRedZombie/status/173847333...,https://twitter.com/LittleRedZombie/status/173...,Sat Dec 23 08:15:16 +0000 2023,"Europe studio visits contd.... \n\nNext stop, ...",en,1,0,0,0,169,0,False,False,"littleredzombies, IOI"
4,https://x.com/LittleRedZombie/status/173820844...,https://twitter.com/LittleRedZombie/status/173...,Fri Dec 22 14:42:43 +0000 2023,We are excited to share that we had the privil...,en,3,0,0,0,165,0,False,False,

In [40]:
tweet_data[tweet_data['isReply'] == True].sum()

url              0
twitterUrl       0
createdAt        0
text             0
lang             0
likeCount        0
replyCount       0
retweetCount     0
quoteCount       0
viewCount        0
bookmarkCount    0
isReply          0
isPinned         0
hashtags         0
dtype: object

In [41]:
# Since none of the tweets are replies, we can drop this column.
tweet_data.drop(columns=['isReply'], inplace=True)

In [42]:
tweet_data.isnull().sum()

url              0
twitterUrl       0
createdAt        0
text             0
lang             0
likeCount        0
replyCount       0
retweetCount     0
quoteCount       0
viewCount        0
bookmarkCount    0
isPinned         0
hashtags         0
dtype: int64

In [43]:
tweet_data.duplicated().sum()

np.int64(188)

In [45]:
tweet_data.drop_duplicates(inplace=True)
tweet_data.shape

(12, 13)

In [47]:
tweet_data.describe()

,likeCount,replyCount,retweetCount,quoteCount,viewCount,bookmarkCount
count,12.000000,12.000000,12.000000,12.0,12.000000,12.000000
mean,2.166667,0.083333,0.250000,0.0,183.083333,0.083333
std,2.724746,0.288675,0.452267,0.0,86.112462,0.288675
min,0.000000,0.000000,0.000000,0.0,0.000000,0.000000
25%,0.750000,0.000000,0.000000,0.0,151.750000,0.000000
50%,1.500000,0.000000,0.000000,0.0,165.000000,0.000000
75%,3.000000,0.000000,0.250000,0.0,230.750000,0.000000
max,10.000000,1.000000,1.000000,0.0,317.000000,1.000000

In [48]:
tweet_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 0 to 16
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   url            12 non-null     object
 1   twitterUrl     12 non-null     object
 2   createdAt      12 non-null     object
 3   text           12 non-null     object
 4   lang           12 non-null     object
 5   likeCount      12 non-null     int64
 6   replyCount     12 non-null     int64
 7   retweetCount   12 non-null     int64
 8   quoteCount     12 non-null     int64
 9   viewCount      12 non-null     int64
 10  bookmarkCount  12 non-null     int64
 11  isPinned       12 non-null     bool
 12  hashtags       12 non-null     object
dtypes: bool(1), int64(6), object(6)
memory usage: 1.2+ KB

In [46]:
mean, std = tweet_data['likeCount'].mean(), tweet_data['likeCount'].std()
print(f"TWITTER\nLikes\nMean: {mean}, Std: {std}")
mean, std = tweet_data['replyCount'].mean(), tweet_data['replyCount'].std()
print(f"Replies\nMean: {mean}, Std: {std}")
mean, std = tweet_data['retweetCount'].mean(), tweet_data['retweetCount'].std()
print(f"Retweets\nMean: {mean}, Std: {std}")
mean, std = tweet_data['quoteCount'].mean(), tweet_data['quoteCount'].std()
print(f"Quotes\nMean: {mean}, Std: {std}")
mean, std = tweet_data['viewCount'].mean(), tweet_data['viewCount'].std()
print(f"Views\nMean: {mean}, Std: {std}")
mean, std = tweet_data['bookmarkCount'].mean(), tweet_data['bookmarkCount'].std()
print(f"Bookmarks\nMean: {mean}, Std: {std}")

TWITTER
Likes
Mean: 2.1666666666666665, Std: 2.7247463045653304
Replies
Mean: 0.08333333333333333, Std: 0.28867513459481287
Retweets
Mean: 0.25, Std: 0.45226701686664544
Quotes
Mean: 0.0, Std: 0.0
Views
Mean: 183.08333333333334, Std: 86.11246170332178
Bookmarks
Mean: 0.08333333333333333, Std: 0.28867513459481287

In [49]:
tweet_data.to_excel(common_path / 'Data' / 'cleaned' / 'twitter_clean.xlsx', index=False)
print("Done:", tweet_data.shape)

Done: (12, 13)

#### ArtStation Data

In [50]:
art_data = pd.read_excel(common_path / 'Data' / 'raw' / 'dataset-artstation-manual.xlsx')

In [51]:
art_data.shape

(61, 10)

In [52]:
art_data.describe()

              views        likes     comments  number of images
count     61.000000    61.000000    61.000000         61.000000
mean    5117.245902   397.196721    37.163934          4.770492
std     7371.455093   599.722347   259.065705          3.018794
min      827.000000    57.000000     0.000000          1.000000
25%     1700.000000    98.000000     0.000000          3.000000
50%     2600.000000   181.000000     1.000000          3.000000
75%     5200.000000   461.000000     2.000000          6.000000
max    36800.000000  3600.000000  2025.000000         14.000000

In [53]:
art_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   project title     61 non-null     object
 1   game              61 non-null     object
 2   client            61 non-null     object
 3   date published    61 non-null     object
 4   views             61 non-null     int64
 5   likes             61 non-null     int64
 6   comments          61 non-null     int64
 7   content type      61 non-null     object
 8   number of images  61 non-null     int64
 9   url               61 non-null     object
dtypes: int64(4), object(6)
memory usage: 4.9+ KB

In [54]:
mean, std = art_data['views'].mean(), art_data['views'].std()
print(f"ARTSTATION\nViews\nMean: {mean}, Std: {std}")
mean, std = art_data['likes'].mean(), art_data['likes'].std()
print(f"Likes\nMean: {mean}, Std: {std}")
mean, std = art_data['comments'].mean(), art_data['comments'].std()
print(f"Comments\nMean: {mean}, Std: {std}")
mean, std = art_data['number of images'].mean(), art_data['number of images'].std()
print(f"Number of Images\nMean: {mean}, Std: {std}")

ARTSTATION
Views
Mean: 5117.245901639344, Std: 7371.455093027739
Likes
Mean: 397.1967213114754, Std: 599.7223474150943
Comments
Mean: 37.16393442622951, Std: 259.06570468563046
Number of Images
Mean: 4.770491803278689, Std: 3.0187935924965723

In [55]:
# Since the data was manually collected, it's clean. 
art_data.to_excel(common_path / 'Data' / 'cleaned' / 'artstation_clean.xlsx', index=False)
print("Done:", art_data.shape)

Done: (61, 10)

In [56]:
insta_data.info() # Instagram data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   shortCode      135 non-null    object
 1   url            135 non-null    object
 2   type           135 non-null    object
 3   timestamp      135 non-null    object
 4   likesCount     135 non-null    int64
 5   commentsCount  135 non-null    int64
 6   caption        135 non-null    object
 7   hashtags       135 non-null    object
dtypes: int64(2), object(6)
memory usage: 8.6+ KB

In [57]:
tweet_data.info() # X/Twitter data

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 0 to 16
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   url            12 non-null     object
 1   twitterUrl     12 non-null     object
 2   createdAt      12 non-null     object
 3   text           12 non-null     object
 4   lang           12 non-null     object
 5   likeCount      12 non-null     int64
 6   replyCount     12 non-null     int64
 7   retweetCount   12 non-null     int64
 8   quoteCount     12 non-null     int64
 9   viewCount      12 non-null     int64
 10  bookmarkCount  12 non-null     int64
 11  isPinned       12 non-null     bool
 12  hashtags       12 non-null     object
dtypes: bool(1), int64(6), object(6)
memory usage: 1.2+ KB

In [58]:
link_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   url             53 non-null     object
 1   text            53 non-null     object
 2   postedAtISO     53 non-null     object
 3   numLikes        53 non-null     int64
 4   numComments     53 non-null     int64
 5   numShares       53 non-null     int64
 6   type            53 non-null     object
 7   document/title  53 non-null     object
dtypes: int64(3), object(5)
memory usage: 3.4+ KB

In [59]:
art_data.info() #Artstation data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   project title     61 non-null     object
 1   game              61 non-null     object
 2   client            61 non-null     object
 3   date published    61 non-null     object
 4   views             61 non-null     int64
 5   likes             61 non-null     int64
 6   comments          61 non-null     int64
 7   content type      61 non-null     object
 8   number of images  61 non-null     int64
 9   url               61 non-null     object
dtypes: int64(4), object(6)
memory usage: 4.9+ KB